format = " $directory$git_branch$git_status\n $character"

[directory]
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
style = "bold magenta"
symbol = ""
format = "[$symbol$branch]($style) "

[git_status]
style = "bold red"
format = "[$all_status$ahead_behind]($style)"
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
untracked = "?"
stashed = "$"
modified = "*"
staged = "+"
renamed = "»"
deleted = "✘"

[character]
success_symbol = "[❯](bold magenta)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold green)"
